language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
after_success:
  - go build -o addup-linux-amd64
deploy:
  provider: releases
  api_key:
    secure: oPVhgwFWro0LszgE10IN7+fyLa/3rftRnQeK9lJ+rEvYZ5GTDfPxQOM9h6OXJ+R8UHdUi92ySZdTi7cfCPWwlTScBAy+YL24XNAcABKEyguEvSSNYBsj+OYWLDUwuxz67ecUPXsfuUVJa73zAqSbe3TUwOgUWHeR51CijzyW6sGBAuwXFPl6o/KklddV68qIq5HrjxFZzCgN5h3804ciSpQ/3KJmonW+cu5Yq881yUlaPQ6ZVlNBKHTsDFdV2D95uln++e3/nt+Dc8GNjIl0I+85w+t8NCG8CcXY5IuDPCAuRD1QVEt1LC57h8Oa7Ju5noq5/F4isY/nn9dOPGfu45zMP1G/vRbd3Kg8VgpNz6BfLy5qdC9hJrnYrJmNZJkhwoD09jGL5bdTG/hdMVqlJScww8JnUdkbMRI/Fs1ldDyCCwtE/SPSf7gYKNNaPCKU6PRCEfXkXPLdkI7cqi7TDjd8MFUHdaTnmEI+n64pE9eD01o+JHNQxp/gBPN5cPnGYIUO+YFuVNpmaWpgMo5ZinIbWQvcEOhUiWhqNtfv5l+iHNPJK4SDx6WPrpklsvQKwnXg5OWK+kWV9dShM+o49kGzgDvLnm3f/d6XQx//uv5zo4zuh1qd+tm1pPm9G1Mu502lbuhC8UXl6/YPSEwv9Dw5mi+JRaTXpd220+WxbxE=
  file:
    - addup-linux-amd64
  skip_cleanup: true
  on:
    tags: true
    go: 1.5
